"""Streamlit app for running the EHR likely DRE pipeline."""

from __future__ import annotations

from datetime import UTC, datetime
import json
from pathlib import Path
import sys
import tempfile
from typing import Any

import pandas as pd
import streamlit as st


def find_project_root(start: Path) -> Path:
    """Find the project root containing pyproject.toml and src."""

    for path in [start, *start.parents]:
        if (path / "pyproject.toml").exists() and (path / "src").exists():
            return path
    raise RuntimeError("Could not find project root containing pyproject.toml and src.")


PROJECT_ROOT = find_project_root(Path(__file__).resolve())
SRC_PATH = PROJECT_ROOT / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from core.contracts import RunContextRecord  # noqa: E402
from datasets import EHRPipelineInputConfig, EHRPipelineRunner  # noqa: E402
from ingestion import TableLoadRequest  # noqa: E402
from reporting import RunSummaryWriter  # noqa: E402


def save_uploaded_file(uploaded_file: Any, destination: Path) -> Path:
    """Persist one Streamlit upload and return its path."""

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(uploaded_file.getvalue())
    return destination


def build_table_request(
    path: Path,
    required_columns: list[str],
    parse_date_columns: list[str],
) -> TableLoadRequest:
    """Build a table loading request for an uploaded CSV."""

    return TableLoadRequest(
        path=str(path),
        file_format="csv",
        required_columns=required_columns,
        parse_date_columns=parse_date_columns,
    )


def build_run_context(run_id: str) -> RunContextRecord:
    """Build a run context for one app execution."""

    return RunContextRecord(
        run_id=run_id,
        project_name="dre_production",
        stage_name="streamlit_ehr_app",
        seed=42,
        timestamp_utc=datetime.now(UTC),
        metadata={"app": "streamlit_app.py"},
    )


def build_input_config(
    dataset_name: str,
    run_output_dir: Path,
    diagnoses_path: Path,
    medications_path: Path,
    seizure_events_path: Path | None,
) -> EHRPipelineInputConfig:
    """Build the EHR pipeline input config from uploaded CSV paths."""

    seizure_request = (
        build_table_request(
            path=seizure_events_path,
            required_columns=["patient_id"],
            parse_date_columns=["event_time"],
        )
        if seizure_events_path is not None
        else None
    )
    return EHRPipelineInputConfig(
        dataset_name=dataset_name,
        diagnoses_request=build_table_request(
            path=diagnoses_path,
            required_columns=["patient_id", "diagnosis_code"],
            parse_date_columns=["diagnosis_time"],
        ),
        medications_request=build_table_request(
            path=medications_path,
            required_columns=["patient_id", "medication_name"],
            parse_date_columns=["medication_start", "medication_end"],
        ),
        seizure_events_request=seizure_request,
        output_dir=str(run_output_dir / "ehr_pipeline"),
    )


def load_json_if_exists(path_value: str | None) -> dict[str, Any] | None:
    """Load a JSON file if the path exists."""

    if path_value is None:
        return None
    path = Path(path_value)
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def write_reporting_bundle(
    run_result: Any,
    run_context: RunContextRecord,
    dataset_name: str,
    output_dir: Path,
) -> Path:
    """Write a compact reporting bundle for the app run."""

    writer = RunSummaryWriter()
    pipeline_summary = writer.build_pipeline_summary(
        run_result=run_result,
        run_context=run_context,
        dataset_name=dataset_name,
    )
    bundle = writer.build_reporting_bundle(
        pipeline_summary=pipeline_summary,
        notes=["Generated by Streamlit EHR app."],
    )
    return writer.write_reporting_bundle(bundle, output_dir / "reporting_bundle.json")


def read_bytes_if_exists(path_value: str | None) -> bytes | None:
    """Return file bytes for download when the path exists."""

    if path_value is None:
        return None
    path = Path(path_value)
    if not path.exists():
        return None
    return path.read_bytes()


def download_if_available(label: str, path_value: str | None, mime: str) -> None:
    """Render a download button for an existing output file."""

    data = read_bytes_if_exists(path_value)
    if data is None:
        st.caption(f"{label} is not available.")
        return
    path = Path(path_value)
    st.download_button(
        label=label,
        data=data,
        file_name=path.name,
        mime=mime,
    )


def create_run_directory(output_root: Path, run_id: str, keep_artifacts: bool) -> Path:
    """Create a durable or temporary run directory."""

    output_root.mkdir(parents=True, exist_ok=True)
    if keep_artifacts:
        run_dir = output_root / run_id
        run_dir.mkdir(parents=True, exist_ok=True)
        return run_dir
    return Path(tempfile.mkdtemp(prefix=f"{run_id}-", dir=output_root))


st.set_page_config(
    page_title="Likely DRE EHR Analyzer",
    layout="wide",
)

st.title("Likely DRE EHR Analyzer")
st.write(
    "`likely_dre` is a computable inference from structured longitudinal patient data. "
    "It is not a formal adjudicated ILAE drug-resistant epilepsy diagnosis."
)

with st.sidebar:
    st.header("Run Configuration")
    dataset_name = st.text_input("Dataset name", value="streamlit_ehr_dataset")
    default_run_id = f"streamlit-ehr-{datetime.now(UTC).strftime('%Y%m%dT%H%M%SZ')}"
    run_id = st.text_input("Run ID", value=default_run_id)
    output_root_text = st.text_input("Output directory", value="outputs/streamlit_runs")
    keep_artifacts = st.checkbox("Keep output artifacts on disk", value=True)

    with st.expander("Advanced settings"):
        st.caption(
            "Expected CSV columns are fixed for this first app version. "
            "Diagnoses need patient_id and diagnosis_code. "
            "Medications need patient_id and medication_name. "
            "Seizure events need patient_id when provided."
        )

st.subheader("Upload EHR CSV Files")
st.write(
    "Diagnoses and medications are required. Seizure events are optional, but missing "
    "events can reduce evidence for persistent seizure burden."
)

upload_cols = st.columns(3)
with upload_cols[0]:
    diagnoses_upload = st.file_uploader("Diagnoses CSV", type=["csv"])
with upload_cols[1]:
    medications_upload = st.file_uploader("Medications CSV", type=["csv"])
with upload_cols[2]:
    seizure_events_upload = st.file_uploader("Seizure events CSV", type=["csv"])

run_clicked = st.button("Run likely DRE analysis", type="primary")

if run_clicked:
    if diagnoses_upload is None or medications_upload is None:
        st.warning("Upload diagnoses and medications CSV files before running analysis.")
        st.stop()

    output_root = Path(output_root_text).expanduser()
    if not output_root.is_absolute():
        output_root = PROJECT_ROOT / output_root
    run_dir = create_run_directory(output_root.resolve(), run_id, keep_artifacts)
    upload_dir = run_dir / "uploads"

    try:
        diagnoses_path = save_uploaded_file(diagnoses_upload, upload_dir / "diagnoses.csv")
        medications_path = save_uploaded_file(
            medications_upload,
            upload_dir / "medications.csv",
        )
        seizure_events_path = (
            save_uploaded_file(
                seizure_events_upload,
                upload_dir / "seizure_events.csv",
            )
            if seizure_events_upload is not None
            else None
        )

        run_context = build_run_context(run_id)
        input_config = build_input_config(
            dataset_name=dataset_name,
            run_output_dir=run_dir,
            diagnoses_path=diagnoses_path,
            medications_path=medications_path,
            seizure_events_path=seizure_events_path,
        )

        with st.spinner("Running EHR likely DRE pipeline..."):
            run_result = EHRPipelineRunner().run(
                input_config=input_config,
                run_context=run_context,
            )

        if run_result.patient_dataset_path is None:
            st.error("The pipeline finished without producing a patient dataset.")
            st.stop()

        patient_dataset_path = Path(run_result.patient_dataset_path)
        if not patient_dataset_path.exists():
            st.error(f"Expected patient dataset is missing: {patient_dataset_path}")
            st.stop()

        patient_df = pd.read_csv(patient_dataset_path)
        reporting_bundle_path = write_reporting_bundle(
            run_result=run_result,
            run_context=run_context,
            dataset_name=dataset_name,
            output_dir=run_dir / "reports",
        )
        reporting_bundle = load_json_if_exists(str(reporting_bundle_path))
        artifact_registry = load_json_if_exists(run_result.artifact_registry_path)
        run_manifest = load_json_if_exists(run_result.run_manifest_path)

        st.success("Likely DRE analysis completed.")

        metric_cols = st.columns(3)
        metric_cols[0].metric("Patient rows", run_result.patient_dataset_row_count)
        metric_cols[1].metric("Likely DRE positive", run_result.likely_dre_positive_count)
        metric_cols[2].metric("Likely DRE negative", run_result.likely_dre_negative_count)

        st.subheader("Patient-Level Results")
        st.dataframe(patient_df, use_container_width=True)

        st.subheader("Artifact Paths")
        artifact_paths = {
            "patient_dataset": run_result.patient_dataset_path,
            "dataset_profile": run_result.dataset_profile_path,
            "artifact_registry": run_result.artifact_registry_path,
            "run_manifest": run_result.run_manifest_path,
            "reporting_bundle": str(reporting_bundle_path),
        }
        st.json({key: value for key, value in artifact_paths.items() if value is not None})

        with st.expander("Run summary"):
            st.json(
                {
                    "run_result": run_result.to_dict(),
                    "reporting_bundle": reporting_bundle,
                    "run_manifest": run_manifest,
                    "artifact_registry": artifact_registry,
                }
            )

        st.subheader("Downloads")
        download_cols = st.columns(4)
        with download_cols[0]:
            download_if_available(
                "Download patient dataset",
                run_result.patient_dataset_path,
                "text/csv",
            )
        with download_cols[1]:
            download_if_available(
                "Download run manifest",
                run_result.run_manifest_path,
                "application/json",
            )
        with download_cols[2]:
            download_if_available(
                "Download artifact registry",
                run_result.artifact_registry_path,
                "application/json",
            )
        with download_cols[3]:
            download_if_available(
                "Download reporting bundle",
                str(reporting_bundle_path),
                "application/json",
            )

        if not keep_artifacts:
            st.info(
                "This run used a temporary directory under the selected output root. "
                "Download needed files before clearing the Streamlit session."
            )

    except Exception as exc:
        st.error("The backend pipeline failed.")
        st.exception(exc)

st.subheader("Limitations")
st.write(
    "`likely_dre` is a computable inference, not formal adjudicated ILAE DRE. "
    "Results depend on structured input quality and available longitudinal evidence. "
    "This first app supports the EHR path only. MRI, EEG, and multimodal UI can come later."
)
